
services:
  ide:
    build:
      context: mock_dev_env
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PASSWORD=12345
    volumes:
      - ./:/home/coder/workspace